name: Build Windows Executable

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --hidden-import=pandas --hidden-import=numpy --hidden-import=tkinter contar_cpfs_xml_gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: contar-cpfs-xml-gui-windows
        path: dist/contar_cpfs_xml_gui.exe
